// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'apikey'
    appId: '1:228057687163:web:9a665d5e27518a20ab6ede',
    messagingSenderId: '228057687163',
    projectId: 'fir-af993',
    authDomain: 'fir-af993.firebaseapp.com',
    storageBucket: 'fir-af993.appspot.com',
    measurementId: 'G-TDL76GEZF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'apikey',
    appId: '1:228057687163:android:32d11042f5e28d14ab6ede',
    messagingSenderId: '228057687163',
    projectId: 'fir-af993',
    storageBucket: 'fir-af993.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'apikey',
    appId: '1:228057687163:ios:2a705735157a4ca2ab6ede',
    messagingSenderId: '228057687163',
    projectId: 'fir-af993',
    storageBucket: 'fir-af993.appspot.com',
    iosBundleId: 'com.example.shoppingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxvh9Rxmz52sQIq2XPGpUpHeHsDIFw0CA',
    appId: '1:228057687163:ios:2a705735157a4ca2ab6ede',
    messagingSenderId: '228057687163',
    projectId: 'fir-af993',
    storageBucket: 'fir-af993.appspot.com',
    iosBundleId: 'com.example.shoppingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3QMgBVzzkMiqlER89bT1rPht0ly-bv40',
    appId: '1:228057687163:web:acde3bd593a10cfbab6ede',
    messagingSenderId: '228057687163',
    projectId: 'fir-af993',
    authDomain: 'fir-af993.firebaseapp.com',
    storageBucket: 'fir-af993.appspot.com',
    measurementId: 'G-0K7LELS6Z6',
  );
}
